# Generated by Django 5.2.11 on 2026-02-14 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nezm', models.PositiveIntegerField()),
                ('khalaghiat', models.PositiveIntegerField()),
                ('elmi', models.PositiveIntegerField()),
                ('weighted_total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='grading.reviewassignment')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('nezm_weight', models.FloatField(default=0.2, help_text='وزن معیار نظم (مثال: 0.2 برای 20%)')),
                ('khalaghiat_weight', models.FloatField(default=0.3, help_text='وزن معیار خلاقیت (مثال: 0.3 برای 30%)')),
                ('elmi_weight', models.FloatField(default=0.5, help_text='وزن معیار علمی بودن (مثال: 0.5 برای 50%)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grading.task'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('reviewer', 'task')},
        ),
    ]
