# Generated by Django 5.2.11 on 2026-09-30 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_email_active_code"),
        ("grading", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان تکلیف")),
                (
                    "description",
                    models.TextField(verbose_name="شرح و دستورالعمل تکلیف"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/attachments/",
                        verbose_name="فایل ضمیمه تکلیف",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مهلت ارسال"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100, verbose_name="حداکثر نمره"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assignments",
                        to="account.schoolgroup",
                        verbose_name="گروه\u200cهای مجاز (خالی = همه)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تکلیف",
                "verbose_name_plural": "تکالیف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_file",
                    models.FileField(
                        upload_to="assignments/submissions/", verbose_name="فایل ارسالی"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="توضیحات دانش\u200cآموز"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین زمان ارسال"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "ارسال شده (در انتظار بررسی)"),
                            ("graded", "تصحیح شده"),
                            ("needs_revision", "نیاز به اصلاح"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="وضعیت تصحیح",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="نمره ثبت\u200cشده"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, verbose_name="بازخورد و نکات داور/ادمین"
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان نمره\u200cدهی"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="grading.assignment",
                        verbose_name="تکلیف مرتبط",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مصحح",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="account.schoolgroup",
                        verbose_name="گروه دانش\u200cآموزی",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ارسال\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ تکلیف",
                "verbose_name_plural": "پاسخ\u200cهای تکالیف",
                "unique_together": {("assignment", "user")},
            },
        ),
    ]
