# Generated by Django 5.2.11 on 2026-09-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_email_active_code"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان محتوا")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "ویدیو آموزشی"),
                            ("document", "سند / جزوه دانلودی"),
                            ("link", "لینک خارجی"),
                        ],
                        default="video",
                        max_length=20,
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="learning_contents/",
                        verbose_name="فایل ضمیمه یا ویدیو",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="لینک آنلاین ویدیو (آپارات، یوتیوب، و...)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="عمومی (قابل مشاهده برای همه)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ بارگذاری"
                    ),
                ),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="allowed_contents",
                        to="account.schoolgroup",
                        verbose_name="گروه\u200cهای اختصاصی مجاز",
                    ),
                ),
            ],
            options={
                "verbose_name": "محتوای آموزشی",
                "verbose_name_plural": "محتواهای آموزشی",
                "ordering": ["-created_at"],
            },
        ),
    ]
