# Generated by Django 5.2.11 on 2026-02-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='q7IW25VXoeX30Kn4iD38HBsYcPB6lQAk9t3WyAylCqB9aoNd1hAvVtAlcld2jHzn', max_length=64),
        ),
    ]
