# Generated by Django 5.2.11 on 2026-02-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='SwyJ34NraJA5hHH3jGno47yL1cPdk1VIStdhxeXjI9ufsKvqn9cpVaiYP6NpwC4D', max_length=64),
        ),
    ]
