# Generated by Django 5.2.11 on 2026-09-22 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_email_active_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolgroup",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسئول گروه",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                default="k0GYgsQIMTgUg39FPBkEuRiRoCWY0j5oblqxfP4RbrC8D4MXZLZopWzBGPWbvEyd",
                max_length=64,
            ),
        ),
    ]
