# Generated by Django 5.2.11 on 2026-09-22 05:31

import django.core.validators
from django.db import migrations, models


def fix_empty_national_id(apps, schema_editor):
    User = apps.get_model("account", "User")
    User.objects.filter(national_id="").update(national_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_schoolgroup_organizer_alter_user_email_active_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                default="g6rtjxmWkeANGQazil21IjfAGqAD9OMSf31IpFt1uYnMyuf0bHp2HMTwCrpH8Lea",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", message="کد ملی باید ۱۰ رقم باشد"
                    )
                ],
                verbose_name="کد ملی",
            ),
        ),
        migrations.RunPython(fix_empty_national_id, migrations.RunPython.noop),
    ]
