services:
  api:
    build:
      context: ../CNCH
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    container_name: cnch-api
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./db_data:/app/data
      - ./media_data:/app/media
    restart: unless-stopped

  web:
    build:
      context: ../cnch-app
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    container_name: cnch-webapp
    network_mode: host
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
